### PR TITLE
 Handling empty key with value for cookies, fix #2827 

### LINKED ISSUE #2827: Mitmproxy crashes, when setting only value in cookies/set-cookies grideditor
##### Steps to reproduce the problem:

1. Run mitmproxy.
2. Press `n` -> `enter` -> `enter` -> `e` -> `cookies` (or `set-cookies`)
3. You are in grideditor. Press `a`. Choose `Value` column and add any value.
You will see something like:
image

4. Press `q` -> `e` -> `cookies` (or `set-cookies` if you're doing that for it)

Traceback: 
```
Traceback (most recent call last):
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/master.py", line 216, in run
    self.loop.run()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 710, in _loop
    self._entering_idle()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 671, in _entering_idle
    callback()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 564, in entering_idle
    self.draw_screen()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 578, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/widget.py", line 1750, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/widget.py", line 1750, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/listbox.py", line 455, in render
    (maxcol, maxrow), focus=focus)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/listbox.py", line 337, in calculate_visible
    self._set_focus_complete( (maxcol, maxrow), focus )
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/listbox.py", line 702, in _set_focus_complete
    (maxcol,maxrow), focus)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/listbox.py", line 672, in _set_focus_first_selectable
    (maxcol, maxrow), focus=focus)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/listbox.py", line 340, in calculate_visible
    focus_widget, focus_pos = self.body.get_focus()
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/grideditor/base.py", line 227, in get_focus
    self.lst[self.focus]
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/grideditor/base.py", line 83, in __init__
    w = self.editor.columns[i].Display(v)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/grideditor/col_text.py", line 18, in Display
    return TDisplay(data, self.encoding_args)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/grideditor/col_text.py", line 31, in __init__
    super().__init__(data.encode(*self.encoding_args))
AttributeError: 'NoneType' object has no attribute 'encode'
```
You can also reproduce it for `set-cookies attributes`. Just add value without name into `set-cookies attributes`. Press `q` -> `q` to get into `flowview` tab. Press `e` -> `set-cookies`. You will see the same traceback.
##### Any other comments? What have you tried so far?

This issue is relevant for 2.0.x as well.

##### System information

Mitmproxy: 3.0.0.dev75 (commit 02d2ef7) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-112-generic-x86_64-with-Ubuntu-16.04-xenial

### PR DESCRIPTION
**Pull request by kira0204**
Fixes #2827 ,
The earlier solution I implemented was bad. I think this will do a decent job.  

Thankyou so much @kajojify for helping out on the flow of the code :)

### CODE REVIEW

**Comment by mhils** [comment]
Thanks! This is a super messy problem in general (see https://inikulin.github.io/cookie-compat/), but for mitmproxy we should provide users with the option to violate standards to some extent. 

Regarding the PR, there' a bit of inconsistency with https://github.com/mitmproxy/mitmproxy/pull/2847/files#diff-e56e7f013477856ed66e296b6c91b1b4L19. My feeling is that it makes most sense to return `""` in both cases, but I haven't really looked into it. Can you two figure that out? :)

**Comment by kira0204** [comment]
Hi, I did not change the code to return `""` in both cases because keeping `=abc` case aside, I wanted `None` to indicate an absence of either key or value or both. Given the case of an empty cookie, the list prepared from the cookie might look like `["",""]` which I feel is not the best way to represent an empty cookie. 
There are numerous ways in which we can tackle the situation keeping all the test cases in mind.
@kajojify What do you think?

**Comment by kajojify** [comment]
@kira0204 sorry for late response. I was busy with the university stuff :( 
I think we should follow general style. 
If we decide to indicate an absence of either key or value or both using `None`, then we have to do this in all cases. 
If we decide to indicate it using `""`, then let's do this in all cases.

An absence of `value` is indicated using `""`:
https://github.com/mitmproxy/mitmproxy/blob/master/test/mitmproxy/net/http/test_cookies.py#L90
I think it is logical to indicate an absence of `key` using `""` as well.

Talking about this https://github.com/mitmproxy/mitmproxy/pull/2847/files#diff-e56e7f013477856ed66e296b6c91b1b4L19.
It must be changed to `""`. It isn't good cookie, since it hasn't key or value, therefore we can't say there isn't key (or value) and use `None` to show this (as you wanted) :) 
By the way it produces new bug:
1. Make a request with pathoc: `pathoc -c example.com:80 localhost:8080 'get:/:h"cookie"="one"'`
2. Open cookie grideditor and mitmproxy will be broken with the traceback as well as here https://github.com/mitmproxy/mitmproxy/issues/2827

By the way, you didn't add `=abc` case to all tests.
Putting `=uno` only to `cookie_pairs`, we test it only in 2 tests:
https://github.com/mitmproxy/mitmproxy/blob/master/test/mitmproxy/net/http/test_cookies.py#L115-L132
But I think, we want to test more :)

**Comment by kira0204** [comment]
Ah, I see. Let's go forward with `""` in all the cases then, I will make the necessary changes and submit a PR.

Btw nice catch on the `"one"` testcase ;) I saw that I was only testing for the `cookie` and not for `set-cookie`, thanks :)

**Comment by tran-tien-dat** [comment]
Just come across this PR after I have done mine, which is supposed to fix #2829. So actually #2829 and #2827 are related. Can you guys take a look at my solution at #2859. Thank you.

**Comment by mhils** [comment]
This looks good now - thank you @kira0204 and @kajojify! 🍰 

@tran-tien-dat: Sorry for the race condition - I'll merge this into master, can you work on top of it?

**Pull request merged**
