### PR TITLE
Setting SIG_IGN for SIGPIPE errors

### PR DESCRIPTION
**Pull request by changsin**
The issue was reported in https://github.com/mitmproxy/mitmproxy/issues/6744

    Problem description:
    When there is a sudden surge of requests, mitmproxy will hit SIGPIPE (broken pipe) errors because it was trying to write to a closed socket. The stacktrace is:
    File "asyncio/runners.py", line 44, in run
    File "asyncio/base_events.py", line 636, in run_until_complete
    File "asyncio/base_events.py", line 603, in run_forever
    File "asyncio/base_events.py", line 1909, in _run_once
    File "asyncio/events.py", line 80, in _run
    File "mitmproxy/proxy/server.py", line 294, in handle_connection
    File "mitmproxy/proxy/server.py", line 407, in server_event
    File "asyncio/streams.py", line 325, in write
    File "asyncio/selector_events.py", line 924, in write

    When this happens, the process terminates unless handled
    The fix will allow the process to continue to run.

#### Checklist

 - [ ] I have updated tests where applicable.
 - [ ] I have added an entry to the CHANGELOG.

### CODE REVIEW

**Review by mhils — APPROVED** [review]
Thank you very much for the PR! 😃 🍰

**Review by mhils — CHANGES_REQUESTED** [review]
Tests seem to be failing on Windows now. Can you take a look please?

**Comment by changsin** [comment]
Added a check condition for non-Windows platforms since SIGPIPE is not available on Windows

**Review by mhils — APPROVED** [review]
Thanks again!

**Pull request merged**
