### PR TITLE
Consolidate SSL Docs (Take 2)

### PR DESCRIPTION
**Pull request by elitest**
As discussed in #524 this PR includes links to external resources for certificate installation instructions.   You can view the result the compiled/countershape'd output [here](http://secstuff.org/doc/certinstall/ssl.html).

Thanks!
Jim

### CODE REVIEW

**Comment by mhils** [comment]
Looks good to me. @cortesi?

**Comment by elitest** [comment]
Based on the testing done in #551, I added a link to the docs for Chrome on Linux.  I looked at some of the [reverse dependencies on ca-certificates](https://gist.github.com/elitest/8e12d38c5f90d448f03e) and there are quite a few, so I think the link for modifying ca-certificates could stay in therebut I'm open to removing it, as a tonne of them are so in the bowels of the OS when compared to a web browser, that if you are trying to do TLS stuff through a proxy, you will probably have the technical sophistication to figure it out. Anyway feedback is appreciated.

Thanks!
Jim

**Comment by elitest** [comment]
Where do we stand with this PR?

**Comment by cortesi** [comment]
Hi Jim. Apologies for taking so long to get to this changeset. I've got a day cleared on Friday to prep for the next release - I'll merge this delta and do some work on the docs myself then.

**Comment by cortesi** [comment]
Merged (finally!). Thanks for your work on this Jim.

**Pull request merged**
