### PR TITLE
Fixes #2495

### LINKED ISSUE #2495: Keyerror in compat 0.17 - peer_address
I get this error when loading an old 0.17 dump file:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/2.0.2/bin/mitmdump", line 11, in <module>
    load_entry_point('mitmproxy==2.0.2', 'console_scripts', 'mitmdump')()
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/main.py", line 120, in mitmdump
    master = dump.DumpMaster(dump_options, server)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/tools/dump.py", line 55, in __init__
    self.load_flows_file(options.rfile)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/master.py", line 182, in load_flows_file
    return self.load_flows(freader)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/master.py", line 164, in load_flows
    for i in fr.stream():
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/io.py", line 42, in stream
    data = io_compat.migrate_flow(data)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/io_compat.py", line 152, in migrate_flow
    flow_data = converters[flow_version[:2]](flow_data)
  File "/usr/local/Cellar/mitmproxy/2.0.2/libexec/lib/python3.6/site-packages/mitmproxy/io_compat.py", line 61, in convert_017_018
    data["server_conn"]["ip_address"] = data["server_conn"].pop("peer_address")
KeyError: 'peer_address'
```

##### Steps to reproduce the problem:

1. Create an outfile with mitmproxy 0.17
2. Open with mitmdump 2.0.2
3. Get a keyerror on "peer_address"

##### Any other comments? What have you tried so far?

Was told on slack to create an issue, however I can't supply the test files because they contain sensitive data.

##### System information

$ /usr/local/Cellar/mitmproxy/2.0.2/bin/mitmdump --version
Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.2
Platform: Darwin-16.7.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0f  25 May 2017
Mac version: 10.12.6 ('', '', '') x86_64

### PR DESCRIPTION
**Pull request by ujjwal96**
Fixes #2495

### CODE REVIEW

**Comment by mhils** [comment]
`data["server_conn"]["ip_address"]` is not optional I think, so we should better make it a placeholder value? `192.0.2.123` would be suitable (https://tools.ietf.org/html/rfc5737) for example.

**Comment by ujjwal96** [comment]
We do set it to None [here](https://github.com/mitmproxy/mitmproxy/pull/2509/files#diff-a09558501d2dd8573d7df9640fa3e126L52) when converting from 0.16 to 0.17
I think placeholder will be better though :+1:

**Comment by ujjwal96** [comment]
Should I change it [here](https://github.com/mitmproxy/mitmproxy/pull/2509/files#diff-a09558501d2dd8573d7df9640fa3e126L52) as well?

**Comment by mhils** [comment]
Nevermind. It's clearly optional at the moment then, so this PR is good as-is. If we ever get around to actually implement proper "optionality" with not-None checks in the code, we need a migration for that anyways.

**Pull request merged**
