### PR TITLE
Exit with meaningful exit codes when we cannot write logs, fixes #4669

### LINKED ISSUE #4669: mitmdump jumps to 100% CPU when parent process exits
#### Problem Description

It took me two days to make this reproduce in isolation. I hope someone with Python skills can figure out what is happening here. Depending on what the root cause is this might not even be related to my funny architecture.

I'm spawning `mitmdump` from Node.js. If the node process exits mitmdump will be re-assigned to become a child of `systemd` (some unix wizardry). It will then immediately jump to 100% CPU and stay there. This _only_ happens when an addon is using at least one network event (go figure...). E.g. I'm using `client_connected` (works with `clientconnect` on v6 as well). If the addon is only using sth. like `running` the bug does not occur. Even better: if the addon originally only has "running" nothing bad happens. But if I then add a `client_connected` and save the file (and the addon is automatically reloaded) it will instantly jump to 100% CPU.

My guess is that it might be related to stdout and the switcheroo with the parent process? In my actual architecture the mitmdump process will poll the parent via gRPC every second and shutdown if it's gone. But the 100% CPU prevents that.

Update: while trying to write down the exact steps it turns out this might only reproduce via local venv and and not if you download the binary. I'm not sure, it's confusing. I'm confused. But I have video proof, so I'm not completely insane.

#### Steps to reproduce the behavior:

index.js

```js
const path = require('path');
const { spawn } = require('child_process');

function handleStdOut(data) {
  console.log(`mitmdump stdout: ${data}`);
}

function handleStdError(data) {
  console.error(`mitmdump stderr: ${data}`);
}

function handleExit(code) {
  console.log(`mitm process exited with code ${code}`);
}

const mitm = spawn(
  // Adjust this path
  '/home/alex/Projects/Bandsalat/src/forks/mitmproxy/venv/bin/mitmdump',
  ['--quiet', '--set', 'connection_strategy=lazy', '--scripts', 'addon.py'],
  {
    detached: true,
    windowsHide: true,
    env: {
      PYTHONUNBUFFERED: '1',
    },
  }
);

console.log(mitm.spawnargs);

mitm.unref();
mitm.on('exit', handleExit);
mitm.stdout.on('data', handleStdOut);
mitm.stderr.on('data', handleStdError);
```
addon.py

```py
class MyAddon:
  def running(self):
    print('running')

  def client_connected(self, client):
    print('client_connected')

addons = [
  MyAddon()
]
```

1. I'm on Ubuntu
2. Adjust index.js to point to your local mitmproxy git venv
3. Launch `node index.js` (Node 14 or 16 work both for me)
4. Now open Chromium with mitmproxy configured. You don't need to enter any URL, Chromium will phone home anyway.
5. Keep Chromium open and ctrl+c the node process
6. Observe your fan getting louder and `top` showing mitmdump at 100% CPU

https://user-images.githubusercontent.com/679144/124594746-740a7080-de60-11eb-9ffb-a5fc4b3ba24a.mp4

#### System Information

Happens with both v6 and HEAD.

```
Mitmproxy: 7.0.0.dev (+492, commit af27556)
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.8.0-59-generic-x86_64-with-glibc2.29
```

### PR DESCRIPTION
**Pull request by Prinzhorn**
#### Description

This fixes the 100% CPU loop for me.  I tried to introduce somewhat meaningful exit codes, feel free to change them. `CANNOT_WRITE_TO_DISK` is unused, not sure where that code even is that write the flow files. I ctrl+f for "sys.exit"

### CODE REVIEW

**Review by mhils — COMMENTED** [review]
Looks good % tests.

You can catch `sys.exit()` with pytest like this:
```python
with pytest.raises(SystemExit):
    ...
```

**Comment by Prinzhorn** [comment]
I don't even know were to begin writing tests. What you're saying is I shouldn't use `from multiprocessing import Process` to spawn a process and test the exit code, but instead do something else?

Also when https://github.com/mitmproxy/mitmproxy/issues/4544 gets fixed it'd be great to have a specific exit code for that as well.

**Comment by mhils** [comment]
click.secho

> I don't even know were to begin writing tests. What you're saying is I shouldn't use `from multiprocessing import Process` to spawn a process and test the exit code, but instead do something else?

Correct. Add a test here: https://github.com/mitmproxy/mitmproxy/blob/main/test/mitmproxy/addons/test_termlog.py
Minimal example:

```python
import click
import sys
import pytest

def test_foo(monkeypatch):

	def write_err(*args, **kwargs):
		raise OSError

	monkeypatch.setattr(click, "echo", write_err)

	with pytest.raises(SystemExit):
		foo()


def foo():
	try:
		click.echo("test")
	except OSError:
		sys.exit(1)
```

**Comment by Prinzhorn** [comment]
I wouldn't say I know what I'm doing, but I added a test. Now if we find a more meaningful numbering system we're good to go? I tried to keep related error codes in the same range and leave room to add more.

its-something
.

**Comment by Prinzhorn** [comment]
@mhils can you check this out? The 100% CPU keeps making trouble, now with the e2e tests that don't exit cleanly.

**Comment by Prinzhorn** [comment]
> if you touch test/mitmproxy/utils/test_exit_codes.py and fix the merge conflicts 5133 is good to go

**Review by mhils — APPROVED** [review]

**Comment by Prinzhorn** [comment]
@mhils I just wanted to create a new PR that just fixes the 100% CPU with a hard exit when logging does not work (I don't want to fix these conflict rn and different exit codes are not important at all). But how does that work with #5590? There is no central place any longer?

**Comment by mhils** [comment]
@Prinzhorn: I think what you're looking for is here now: 
https://github.com/mitmproxy/mitmproxy/blob/ca74a2a9cb168260e5f6b0a84de3ab76b9d160c8/mitmproxy/addons/termlog.py#L53-L57

**Comment by Prinzhorn** [comment]
@mhils thanks I created https://github.com/mitmproxy/mitmproxy/pull/5695 . It's probably just a single line you need to adjust to make the test work, I give up for now

**Pull request closed without merging**
