### PR TITLE
[web] Add context menu for flow row

### PR DESCRIPTION
**Pull request by gzzhanghao**
ContextMenuLayer always creates an extra layer when rendering [react-contextmenu/contextmenu-layer.js#L94](https://github.com/vkbansal/react-contextmenu/blob/master/src/contextmenu-layer.js#L94), so we need to put it into FlowColumn instead of FlowRow.

### CODE REVIEW

**Comment by mhils** [comment]
Hm - this clutters things up a bit. Can't we just have a single manual HTML5 `<menu type="context">` for the whole table? As I see it, the only tricky part might be letting the menu know which flow we are on, but this could be solved by listening to https://developer.mozilla.org/de/docs/Web/Events/contextmenu ?

**Comment by gzzhanghao** [comment]
AFAIK, `<menu type="context">` is behind a flag in latest version of chrome and lack of compatibility in most of other browsers. So we still need `react-contextmenu` here.
Maybe we can have a single `ContextMenuWrapper` instead of `ContextMenu`?

**Comment by mhils** [comment]
Looks ok so far. Three issues:

1. Right-clicking a flow does not work if another context menu is present.
2. We should not show things like "Accept" if the flow is accepted.
3. The context menu looks broken to me:

image

**Comment by gzzhanghao** [comment]
1st. It seems to be a feature of `react-contextmenu`, I wonder if there are any method to gracefully hide the backdrop layer :(
Other than that, fixed :tada:

**Pull request closed without merging**
