### PR TITLE
Add examples to Docker image

### PR DESCRIPTION
**Pull request by abitrolly**
Add `examples/` into Docker image.

https://github.com/mitmproxy/mitmproxy/issues/1477#issuecomment-545007956

#### Checklist

 - [x] I have updated tests where applicable.
 - [x] I have added an entry to the CHANGELOG.

### CODE REVIEW

**Comment by abitrolly** [comment]
image

I don't see why CodeCov fails.

**Comment by abitrolly** [comment]
@mhils that's an easy one. )

**Comment by mhils** [comment]
Thanks! 🍰

**Comment by mhils** [comment]
This caused CI to fail on master. I've reverted the commit, feel free to send a new one. :)

**Comment by abitrolly** [comment]
@mhils no idea why it fails. Without `tox` everything works ok. Why use `tox` for Docker image?

**Comment by abitrolly** [comment]
https://github.com/mitmproxy/mitmproxy/blob/1b0fce6abaaf35e28b4f319e2fbc314dad210822/release/cibuild.py#L278-L279

I think the examples should be added here.

**Comment by abitrolly** [comment]
Building with `tox` locally fails.
```
/tmp/amend-pr-4447 (harfix)$ tox -e cibuild -- build     
cibuild create: /tmp/amend-pr-4447/.tox/cibuild
cibuild installdeps: -e.[dev], pyinstaller==4.2, twine==3.4.1, awscli
...
cibuild run-test-pre: PYTHONHASHSEED='234653030'
cibuild run-test: commands[0] | mitmdump --version
Mitmproxy: 7.0.0.dev (+415, commit 8f6cd7c)
Python:    3.9.2
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Linux-5.11.10-200.fc33.x86_64-x86_64-with-glibc2.32
cibuild run-test: commands[1] | python ./release/cibuild.py build
Traceback (most recent call last):
  File "/tmp/amend-pr-4447/./release/cibuild.py", line 512, in <module>
    cli()
  File "/tmp/amend-pr-4447/.tox/cibuild/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/amend-pr-4447/.tox/cibuild/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/amend-pr-4447/.tox/cibuild/lib/python3.9/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/amend-pr-4447/.tox/cibuild/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/amend-pr-4447/.tox/cibuild/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/amend-pr-4447/./release/cibuild.py", line 450, in build
    be.dump_info()
  File "/tmp/amend-pr-4447/./release/cibuild.py", line 156, in dump_info
    print(f"cibuild.{attr}={getattr(self, attr)}", file=fp)
  File "/tmp/amend-pr-4447/./release/cibuild.py", line 257, in version
    raise BuildError("We're on neither a tag nor a branch - could not establish version")
__main__.BuildError: We're on neither a tag nor a branch - could not establish version
ERROR: InvocationError for command /tmp/amend-pr-4447/.tox/cibuild/bin/python ./release/cibuild.py build (exited with code 1)
_______________________________________________________________________________ summary _______________________________________________________________________________
ERROR:   cibuild: commands failed
/tmp/amend-pr-4447 (harfix)$ 
```

**Comment by mhils** [comment]
@abitrolly: Can you remind me what's the purpose of having `examples/` in the Docker image? I initially merged this because I don't have strong opinions here and it seemed straightforward. Thinking about this a bit longer, I don't see what's the purpose here. If you are concerned about HAR support, my reply would be that we should move it into the core anyhow. :)

**Comment by abitrolly** [comment]
@mhils I just want to play with `contrib` scripts without installing anything on my system.

**Comment by mhils** [comment]
I'd recommend you just expose a local copy of `contrib` to your Docker container. :)

**Comment by abitrolly** [comment]
Well, the container at least provides imaginary guarantee that examples within match the version shipped.

**Pull request merged**
