### PR TITLE
New File has been renamed to clear all

### PR DESCRIPTION
**Pull request by yogeshojha**
Issue #4025, #3665  has been fixed by changing the New File to Clear All

Screenshot 2020-06-29 at 6 18 18 PM

### CODE REVIEW

**Comment by mhils** [comment]
Awesome, thanks! 🍰 😃

**Comment by mhils** [comment]
Could you please make sure that the tests pass so that we can get this merged? Thanks!

**Comment by yogeshojha** [comment]
@mhils,

Looks like the build failed due to 

```
->  Pinging Codecov
35
https://codecov.io/upload/v4?package=bash-20200622-40cebbd&token=secret&branch=issue%2Fclearall&commit=936f349bf7d2d6c6f7ad9c9e5ce7ff3674236cc7&build=151433548&build_url=http%3A%2F%2Fgithub.com%2Fmitmproxy%2Fmitmproxy%2Factions%2Fruns%2F151433548&name=macos-latest&tag=&slug=mitmproxy%2Fmitmproxy&service=github-actions&flags=&pr=4051&job=
36
->  Uploading to
37

38
curl: (3) URL using bad/illegal format or missing URL
39
curl: (3) URL using bad/illegal format or missing URL
40
    X> Failed to upload
41
    -> Sleeping for 30s and trying again...
42
codecov.sh: line 1668: [: 0+1: integer expression expected
43
    -> Uploading to Codecov
44
    HTTP 200
45
https://codecov.io/github/mitmproxy/mitmproxy/commit/936f349bf7d2d6c6f7ad9c9e5ce7ff3674236cc7
46
##[error]Codecov failed with the following error: The process 'bash' failed with exit code 1```

Is it specific to Codecov? Can you re-run the github actions tests again?

**Comment by mhils** [comment]
Yes, that should go away with your next push. I'm talking about https://github.com/mitmproxy/mitmproxy/pull/4051/checks?check_run_id=818305276#step:8:189.

**Comment by yogeshojha** [comment]
Thanks for the heads-up! I had forgotten to run the npm test 😄 Looks like the build will pass now!

**Comment by mhils** [comment]
Thanks! :)

**Pull request merged**
