### PR TITLE
Add a section on using Magisk and Magisk modules in the Android howto

### PR DESCRIPTION
**Pull request by Jurrie**
#### Description

Using Magisk and a Magisk module containing the mitmproxy CA certificate, one can use Google Play builds with mitmproxy. Previously, the documentation stated that this is not possible.

#### Checklist

 - [N/A] I have updated tests where applicable.
 - [X] I have added an entry to the CHANGELOG.

### CODE REVIEW

**Comment by mhils** [comment]
Thanks for the PR! I saw you also commented on https://github.com/mitmproxy/mitmproxy/pull/5547/files - could the description benefit from using the Magisk module from mitm.it instead of manually creating one?

**Comment by Jurrie** [comment]
> Thanks for the PR! I saw you also commented on https://github.com/mitmproxy/mitmproxy/pull/5547/files - could the description benefit from using the Magisk module from mitm.it instead of manually creating one?

Yes, the process of creating the Magisk module is about the same. So after merging one of the two PRs, the other should be updated to reflect this in the documentation.

I would propose to merge this one first. If #5547 is then merged later, the part on creating the Magisk module in the document could read something like "or download the Magisk module from the mitmproxy web interface here".

**Comment by mhils** [comment]
#5547 is already merged, so let's adjust here right away. :)

**Comment by Jurrie** [comment]
> #5547 is already merged, so let's adjust here right away. :)

Aah, I somehow totally missed that :see_no_evil: Updated in [0516fb6](https://github.com/mitmproxy/mitmproxy/pull/5924/commits/0516fb6fb4fabd10c86e48ad5ef393f588c1aa32).

**Comment by mhils** [comment]
Awesome, thanks! :cake:

**Pull request merged**
