### PR TITLE
migrated the files to tsx

### PR DESCRIPTION
**Pull request by shubhangi013**
#### Description

Migrated `web/src/js/components/Modal/Modal.jsx` and `web/src/js/components/Modal/ModalLayout.jsx` to typescript.

fixes part of #4971 

#### Checklist

 - [ ] I have updated tests where applicable.
 - [ ] I have added an entry to the CHANGELOG.

### CODE REVIEW

**Comment by shubhangi013** [comment]
@mhils could you review this once? :sweat_smile:

**Review by mhils — COMMENTED** [review]
This looks good overall, thanks! 🍰 

Two last hurdles to get this merged:

1. Please remove the compiled static files from this PR.
2. Let's get the tests fixed. :)

**Comment by shubhangi013** [comment]
> This looks good overall, thanks! cake
> 
> Two last hurdles to get this merged:
> 
>     1. Please remove the compiled static files from this PR.
> 
>     2. Let's get the tests fixed. :)

Should I revert all the changes I've done to the other files than the .tsx files? including those to package-lock.json?

**Comment by mhils** [comment]
Yes please!
We don't update the compiled assets with each commit as that would add too much noise to the repo. At the same time we do want to keep the compiled files in there so that tue Python folks don't need to have npm installed.

**Comment by shubhangi013** [comment]
> Yes please! We don't update the compiled assets with each commit as that would add too much noise to the repo. At the same time we do want to keep the compiled files in there so that tue Python folks don't need to have npm installed.

Ah right! gotcha! :)

**Review by mhils — COMMENTED** [review]
This looks great now except for the failing test at https://github.com/mitmproxy/mitmproxy/runs/4592517504?check_suite_focus=true! 😃

**Comment by shubhangi013** [comment]
> This looks great now except for the failing test at https://github.com/mitmproxy/mitmproxy/runs/4592517504?check_suite_focus=true! smiley

Oh right. I haven't worked with tests :sweat_smile: Can you guide me as what should I do?

**Comment by mhils** [comment]
The Typescript compiler is throwing an error:
```
Error: src/js/components/Modal/Modal.tsx(11,24): error TS2604: JSX element type 'ActiveModal' does not have any construct or call signatures.
```
You can test this locally by running `tsc --noEmit`! :)

**Comment by shubhangi013** [comment]
Screenshot from 2021-12-21 15-10-50
running npm test or tsc --noEmit give me this output in the terminal and show no error in the Modal.tsx :sweat_smile:

**Comment by mhils** [comment]
Not sure what's up there - this might be due to differences in the typescript compiler version maybe? CI uses the versions declared in `package-lock.yml`, so maybe it helps if you delete your node_modules folder and then run `npm ci`. In any case, if you can fix it in a way our CI agrees on, I'm happy as well.

**Comment by shubhangi013** [comment]
> Not sure what's up there - this might be due to differences in the typescript compiler version maybe? CI uses the versions declared in `package-lock.yml`, so maybe it helps if you delete your node_modules folder and then run `npm ci`. In any case, if you can fix it in a way our CI agrees on, I'm happy as well.

Sure I'll do that!

**Review by mhils — APPROVED** [review]
Awesome, thanks! 🍰

**Comment by shubhangi013** [comment]
> Awesome, thanks! 🍰 

Thankyou for being patient with me 😅!

**Pull request merged**
