### PR TITLE
Python 3 - mitmproxy.contentviews

### PR DESCRIPTION
**Pull request by dufferzafar**

### CODE REVIEW

**Comment by dufferzafar** [comment]
Please check if `.decode()` are in the right places.

**Comment by dufferzafar** [comment]
There are a few test files for which all tests already pass. Should I add them to `tox.ini` in this pull itself?

**Comment by Kriechi** [comment]
Yes, please add them - this allows us to detect regressions as soon as possible.
Thanks!

**Comment by dufferzafar** [comment]
Done!

**Comment by Kriechi** [comment]
Merged - Thanks!

**Pull request closed without merging**
