### PR TITLE
fix #2228

### LINKED ISSUE #2228: Sticky cookies are improperly formatted.
##### Steps to reproduce the problem:

1. Go to http://www.html-kit.com/tools/cookietester/
2. Click 'Set Test Cookie'
3. Observe that one cookie is sent to the server.
4. Remove the cookie.
5. launch mitmproxy with `mitmproxy -t html-kit\.com` and tell your browser to use it as a proxy
6. Reload the page.
7. Click 'Set Test Cookie'
8. Observe that two 'cookies' are sent to the server.

##### Any other comments? What have you tried so far?
There appears to be a comma in the output of mitmproxy, even though it is surrounded by quotes. It's possible, then that this is a parsing fail on the tool's end caused by a difference in what's sent back for the format of the date. Still, should it really be changing that?

##### System information
Arch Linux, freshly updated.

Mitmproxy version: 2.0.1 (release version) 
Python version: 3.6.0
Platform: Linux-4.10.6-1-ARCH-x86_64-with-glibc2.3.4
SSL version: OpenSSL 1.0.2k  26 Jan 2017

### PR DESCRIPTION
**Pull request by mhils**

### CODE REVIEW

**Comment by kitling** [comment]
Looks better than my hack, though I'd still like to see some of the other things I mentioned addressed, if it makes sense to do so.

Not personally testing due to OS upheaval.

**Comment by mhils** [comment]
I'm happy for the feedback, but I'm not sure what you are referring to? :)

**Comment by mhils** [comment]
(merging for now to avoid conflicts, still happy about feedback)

**Comment by kitling** [comment]
Just tested, LGTM.

(When I made the comment about "OS Upheaval", I was dealing with the fallout of a bad stick of ram. Protip: if everything is crashing and segfaulting, don't try to run a system upgrade. Was attempting to use OpenBSD for a while, before I just gave up and recovered Arch.)

**Pull request merged**
