### PR TITLE
external-viewer-fix

### PR DESCRIPTION
**Pull request by rjt-gupta**
fix for #3165 

Should this be added in docs?

### CODE REVIEW

**Comment by mhils** [comment]
Looking at the issue again I feel that it may be more useful if we just add a regular mitmproxy console option (https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/console/consoleaddons.py) for this (where we mention the use of $EDITOR in the option description). What do you think?

**Comment by rjt-gupta** [comment]
Yeah I guess this is a better solution.

**Comment by rjt-gupta** [comment]
In my opinion we should only mention MITMPROXY_EDITOR in options as it will set only mitmproxy specific editor. what do you think?

**Comment by mhils** [comment]
Thanks again! 🍰

**Pull request merged**
