### PR TITLE
Make it possible to set sequence options

### LINKED ISSUE #3015: No way to set a sequence option on the command line
##### Steps to reproduce the problem:

1. Create a file `/tmp/example.py` with the following text:
```python
import typing
from mitmproxy import ctx

class Example:

    def load(self, loader):
        loader.add_option(name='myoption', typespec=typing.Sequence[str],
                          default=[], help='')

    def response(self, flow):
        ctx.log.info(repr(ctx.options.myoption))

addons = [Example()]
```
2. Run `mitmdump -s /tmp/example.py --set myoption=foo --set myoption=bar`
3. Run a request through it: `curl -sx http://localhost:8080 http://httpbin.org/get`
4. Observe that `['bar']` is printed, meaning that `myoption` is set to a sequence of one element — the last one passed on the command line, with the first one ignored.

##### Any other comments? What have you tried so far?

Looking at [the code](https://github.com/mitmproxy/mitmproxy/blob/79fc4e8ad6cab5181ba39d7f0b0d40f7c11a8389/mitmproxy/optmanager.py#L312-L316), I’m not immediately sure why the multiple `--set` don’t work as I expected them to.

##### System information

Mitmproxy: 4.0.0 (79fc4e8)
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial

### PR DESCRIPTION
**Pull request by Yopi**
Attempts to fix #3015 through looking at whether or not the option is
of the type Sequence[str].

#### Description

Looks at the type of the option and allows multiple to be set if it is a Sequence. For the unknown options we don't know the type yet, so all of them are assumed to be sequences until the option has been added, and if it's not a sequence we pick the first entry instead.

#### Checklist

 - [X] I have updated tests where applicable.
 - [ ] I have added an entry to the CHANGELOG.

### CODE REVIEW

**Comment by Prinzhorn** [comment]
I can't really judge the implementation itself, but I don't think this is generic enough. What about `Sequence[int]` for example?

**Comment by Yopi** [comment]
> but I don't think this is generic enough. What about Sequence[int] for example?

Currently there is no support for any other Sequence types other than Sequence[str]. As can be seen in optmanager.py:335-367 https://github.com/mitmproxy/mitmproxy/blob/3f60e4d5dbdf2180dec8d75ca0f5a2953fd0ba4b/mitmproxy/optmanager.py#L335-L367

So I don't think this PR needs to be support it either.

**Comment by Prinzhorn** [comment]
I didn't know that. Does that mean the following shouldn't work right now (it does)?

```py
import typing

from mitmproxy import ctx

class MyAddon:
    def load(self, loader):
        loader.add_option(
            name = "my_option",
            typespec = typing.Sequence[int],
            default = [1, 2, 3],
            help = "Example",
        )

        print(ctx.options.my_option)

        ctx.options.update(
            my_option = [7, 8, 9]
        )

        print(ctx.options.my_option)

addons = [
    MyAddon()
]
```

**Comment by Yopi** [comment]
Sorry for the delayed response! I realised that this PR was not working exactly correctly, and I believe it wasn't testing exactly the correct thing. I've gone back and tried a slightly different approach. 

> But still this might be the perfect opportunity to clean this up, make it consistent and fix the multiple options issue. But that's just my wishful thinking 😉

Not sure exactly what you want to be cleaned up. I'm not too familiar with this project to say whether or not it makes sense to add Sequence[bool] or Sequence[int]s before there is an actual need to do so. 

But please do take another look at this PR. I think both the tests and the code makes a bit more sense this time around.

**Comment by mhils** [comment]
Thanks for this really excellent PR and sorry that it took us so long! 😃 🍰

**Pull request merged**
