### PR TITLE
Added --per-host-ciphers-dir option

### PR DESCRIPTION
**Pull request by aGHz**
This adds the ability to specify allowed ciphers on a per-server basis in a similar way to the use of client certificates (see #588 for motivation).

### CODE REVIEW

**Comment by elitest** [comment]
So if I understand this right I would specify a folder which would contain something like ``google.com.cipher``?  In those would be something like ``RC4-SHA:AES128-SHA256``?  Does this work with multiple sites in the directory?

My only other comment with this is that looking at the code this only determines the ciphers used on one side of the proxy.  If I remember how this part of the code works you are setting the ciphers that the client-facing side of the proxy uses to figure out what cipher to send back in the SERVERHELLO.  This does not include what mitmproxy sends to the upstream server, ie. what is specified in the server-facing CLIENTHELLO.  I think it would be better to specify what side of the proxy it is on in the flag and mention it in the help text as well.

**Comment by aGHz** [comment]
Thanks for the comments! You are correct and yes it would work with any sites you put in there. When it tries to connect to a host, it looks in that dir to see if there's an appropriately named file and uses its content to override the generic `--ciphers-server` option.

I must admit my understanding of the code isn't top shape, but from what I gather `ConnectionHandler.server_conn` is the connection **to** the server (i.e. presumably the one where mitmproxy says CLIENTHELLO, I'm not familiar with TLS specifics). So this code would set the ciphers on the connection to the upstream server.

I didn't think it would be useful to add per-client cipher configuration because typically you can control what the client does, and in any case it would be hard to identify the client unless it has a static IP.

**Comment by elitest** [comment]
Ah gotcha, I guess I got mixed up then.

Being able to control the ciphers that my client connects to mitmproxy with is certainly as useful as setting it on the upstream connection.  I find it is often far easier and more temporary to set the cipher through mitmproxy than in the config of a client.  Also not every client is as flexible as a web browser(if you even consider them flexible) in terms of being able to turn off and on ciphers.  I could also specify deprecated or disabled ciphers if I'm compiled against the right version of OpenSSL.

Yeah I find the way we worded ``--ciphers-server`` and ``--ciphers-client`` confusing, as the person who contributed some of that code I have trouble keeping it straight in my head..  Maybe ``--ciphers-pre-proxy`` and ``--ciphers-post-proxy`` would have been better.

**Comment by Kriechi** [comment]
I don't like the idea of using folders and files to specify ciphers...
Did you consider a simple config file, like yaml or json to specify a list of domains + ciphers?
This could probably go int `~/.mitmproxy` with all the other config stuff...

**Comment by mhils** [comment]
We should probably just provide inline script hooks which allow modification of the SSL context.

**Comment by mhils** [comment]
Thanks a lot for the PR @aGHz - As I mentioned in my last comment, this sounds like a feature that's very suitable for an inline script. I'd be happy to accept a PR that exposes the SSL Context to scripts, but I think we don't want to add another command line switch for this. Sorry!

Thanks!
Max

**Pull request closed without merging**
