### PR TITLE
Notify when proxy server started

### LINKED ISSUE #1505: mitmdump should display "ready" message after start.
##### Steps to reproduce the problem:

2. `mitmdump`

##### What is the expected behavior?

mitmdump should print some notification that it is running and ready to receive traffic.

##### What went wrong?

mitmdump just displays nothing, it looks like it hangs.

##### Any other comments? What have you tried so far?

Ideally we'd only show that if mitmdump is invoked in a tty?

---

Mitmproxy Version: 0.18
Operating System: Win10 x64

### PR DESCRIPTION
**Pull request by chhsiao90**
Resolved #1505 

I think use the channel for communication between server and master is a good practice.
But I need your advise for
1. Is the notification message is OK?
2. Is override the serve_forever from TCPServer ok? Or we have some better way to do this.

Thanks!

### CODE REVIEW

**Comment by mhils** [comment]
Thanks for the PR!

This seems to be a bit more complicated than it needs to be. Can we just add a simple print statement [here](https://github.com/mitmproxy/mitmproxy/blob/1e5a5b03f8d56df62a04a368bd5eb2d59cb7582a/mitmproxy/dump.py#L51) that states `"Proxy server listening at http://$options.listen_host:$options.listen_port"`? :-)

**Comment by chhsiao90** [comment]
No problem and done!
Currently, the mitmdump message show as
```
>mitmdump -b 192.168.56.1
Proxy server listening at http://192.168.56.1:8080

>mitmdump
Proxy server listening at http://:8080
```
Is that empty host acceptable or not? Or we should give it a default value?

**Comment by mhils** [comment]
Can we just make it `(self.config.options.listen_host or "0.0.0.0")`?
Also, we should move that to the DumpMaster constructor to keep things simpler. When that code is called we have already initialized the socket, so we are already listening on the proxy port.

**Comment by chhsiao90** [comment]
Done! Please take a look.
Sorry I misunderstood that you mean use print instead of notify.
And I didn't notice that it need to be moved to DumpMaster.

That was make sense! thanks

**Comment by mhils** [comment]
This looks great now, thanks!

**Comment by Kriechi** [comment]
What about https://github.com/mitmproxy/mitmproxy/issues/302?

**Pull request merged**
