### PR TITLE
Fix #6951

### LINKED ISSUE #6951: Show More Not working
I'm trying to look at this WebSocket data in mitmweb, after I click Show More 2 times and the button no longer works. How do I fix this?

### PR DESCRIPTION
**Pull request by Prinzhorn**
#### Description

So, are we not running prettier in autofix? I have prettier on ctrl+s and it reformatted the file. The changes are super simple (use a new `remainingLines` variable).

Also am I supposed to commit the compiled files? They are from watch mode, so not minified I guess?

#### Checklist

 - [ ] I have updated tests where applicable.
 - [ ] I have added an entry to the CHANGELOG.

### CODE REVIEW

**Comment by Prinzhorn** [comment]
> Also am I supposed to commit the compiled files? They are from watch mode, so not minified I guess?

I just read the docs :smile:

**Comment by lups2000** [comment]
can we close this?

**Comment by Prinzhorn** [comment]
> So, are we not running prettier in autofix?

Waiting for a response, there's no hurry to close this

**Comment by mhils** [comment]
We are running prettier in CI (see the autofix commit), but possibly a different version. Let's upgrade to the latest thing once @lups2000' branch is in main :)

**Comment by Prinzhorn** [comment]
@mhils never mind, I thought my editor would only use the project's prettier settings but I do have some overrides. So everything works as expected (autofix is running `npm run prettier` so it's the identical version to locally)

**Pull request closed without merging**
