### PR TITLE
fix #5450, "?" key handling inside overlay page

### LINKED ISSUE #5450: Help window doesn't appear, when changing cofing
#### Problem Description
While changing parameters in options (like allow_hosts or block_list), there is hint on the bottom of the window "No values - you should add some. Press `?` for help."

image

But after I'm pressing `?` - nothing happend. No help window appear.

Then when I'm quit parameter editing, help window for options appear (not for parameter changing window).

image

Looks like something went wrog, because I'm expext help window with hotkeys for adding new hosts.

#### Steps to reproduce the behavior:
1. Type `mitmproxy` in your terminal
2. Press `O`
3. Select `allow_hosts` and press `Enter`
4. Press `?`

**Expected**: Help window appear for `alliow_hosts` window
**Actual**: Nothing happend, help window for `Options` window appear after quit `allow_hosts` window.

#### System Information
Mitmproxy: 8.1.1
Python:    3.10.5
OpenSSL:   OpenSSL 1.1.1q  5 Jul 2022
Platform:  macOS-12.4-arm64-arm-64bit

### PR DESCRIPTION
**Pull request by emanuele-em**
#### Description

this should fix #5450: it handles the '?' key pressing inside overlays by simply pop the overlay window from the windows stack, probably not the best solution but it works

#### Checklist

 - [x] I have updated tests where applicable.
 - [x] I have added an entry to the CHANGELOG.

### CODE REVIEW

**Comment by lups2000** [comment]
Hi @emanuele-em 😃 is there a reason why this PR hasn't been merged yet? Is there anything else to do?

**Comment by emanuele-em** [comment]
Hi @lups2000, actually there is no particular reason on my side, maybe @mhils knows the truth 😆

**Review by mhils — APPROVED** [review]

**Comment by mhils** [comment]
LGTM % rebase :)

**Comment by lups2000** [comment]
should be fine now @mhils , right?

**Pull request merged**
