### PR TITLE
hide local mode on linux in mitmweb

### PR DESCRIPTION
**Pull request by lups2000**
#### Description

In this PR, we hide the local mode when mitmweb is running on Linux. I chose to hide the mode entirely rather than grey it out, as the message "Remaining modes are coming soon" is already present.

#### Checklist

 - [ ] I have updated tests where applicable.
 - [ ] I have added an entry to the CHANGELOG.

### CODE REVIEW

**Review by mhils — COMMENTED** [review]
This is confusing the OS of the browser with the OS of where mitmproxy runs on. I think we need to expose additional backend state here :)

**Comment by lups2000** [comment]
> This is confusing the OS of the browser with the OS of where mitmproxy runs on. I think we need to expose additional backend state here :)

ahh I see, I thought it was much simpler 😄 we can discuss it then

**Comment by lups2000** [comment]
@mhils better now?

**Review by mhils — APPROVED** [review]
Yes, great. Thanks! 🚀

**Pull request merged**
