### PR TITLE
Consolidate SSL documentation

### PR DESCRIPTION
**Pull request by elitest**
As discussed in #516, I have eliminated the platform specific SSL installation instructions.  Combined the Webapp and Overview pages, did a bit of reorganization and cleanup.

### CODE REVIEW

**Comment by mhils** [comment]
Thanks for the PR! I'm in favor of the general change here, but we should be careful that we're not losing important bits. In particular, the docs for Java are quite helpful and not covered by the webapp. Also, I'm not sure about the IOS Simulator. I'll ponder a bit how we can structure this best...

**Comment by elitest** [comment]
Though, to someone who has no experience with certificates the Java documentation is as useful as the caveats in the Android documentation.  I'm not sure that the Java documentation, as an example, tells you anything that you couldn't learn from Oracle's official [root cert documentation](http://docs.oracle.com/cd/E19906-01/820-4916/geygn/index.html).  Perhaps linking to official documentation for instructions on how to manage certificates for those clients that don't work with the webapp might be better?  Or even linking to official docs for instructions for all of the most common platforms that users of mitmproxy would be using?

With the iOS simulator that might cause a problem, as I couldn't find any official docs on installing a custom root cert into the iOS simulator and I'm sure Apple's stance is "Why would you want to do that?".  I have only used the Android simulator, not the iOS one, does it not allow you to use the browser inside the simulator to install root certs?  According to [this](http://codeblog.shape.dk/blog/2014/01/06/custom-ssl-certificate-with-charles-web-proxy/) it is as simple as dragging and dropping the certificate onto the simulator window.

**Comment by mhils** [comment]
I wasn't aware of the Oracle documentation - sure, we should just link to it.

Having a single section "Install certificate manually", which provides links to all the relevant docs seems to be the best solution. I personally don't care if they are official docs, as long as they are good.

**Comment by cortesi** [comment]
For what it's worth, I'm all for pruning back the SSL cert documentation, but I think this will increase our support burden. I'm in favor of: a) removing platform-specific instructions wherever the onboarding app works, b) consolidating all the SSL installation info onto one page, c) simplifying and referring to other documentation where it's good, available, and canonical.

**Comment by elitest** [comment]
Sounds good.  I think the my only hesitation to linking to "not official" documentation is that it raises the risk of that documentation becoming a dead link somewhat.  I closed the pull request as I really needed to properly branch my fork, there are a couple other things I would like to work on as well and having my master locked up in a pull request is preventing that! :)  I'll flesh out the one pager more, and see if I can get something better submitted.

Jim

**Pull request closed without merging**
