### PR TITLE
Web UI shows blank for details tab when server address is blank 

### PR DESCRIPTION
**Pull request by Samhita-sopho**
#### Description

Added a check for server address in details.js #4205 . Opening a new pull request with changes suggested from previous PR .
#### Checklist

 - [x] I have updated tests where applicable.
 - [x] I have added an entry to the CHANGELOG.

### CODE REVIEW

**Comment by Samhita-sopho** [comment]
I suppose the web ui test fails because I have updated the snapshot for detailComponent

**Comment by Samhita-sopho** [comment]
Any updates on how I can fix this further since it does not pass the tests, the snapshots have been updated and it passes the tests locally on updating the snapshots. Looking forward to working more on this

**Comment by Samhita-sopho** [comment]
> #4205

**Comment by mhils** [comment]
Fantastic, thanks for getting this together! 😃 🍰

**Pull request merged**
