### PR TITLE
Bug in expected_http_body_size fix

### PR DESCRIPTION
**Pull request by surajt97**

### CODE REVIEW

**Comment by surajt97** [comment]
Can you help me understand the error in builds?

**Comment by Kriechi** [comment]
Thanks for the PR! 👍 

Looks good so far - the only thing missing is a test to make sure the fix actually works.
Otherwise the builds will not pass... Sorry about that... ☹️ 

Would you mind writing a simple test here?https://github.com/mitmproxy/mitmproxy/blob/master/test/mitmproxy/net/http/http1/test_read.py

**Comment by surajt97** [comment]
@Kriechi done.

**Comment by Kriechi** [comment]
Thanks - Perfect! 👍 🎉

**Pull request merged**
