### PR TITLE
web: Fix #1888

### LINKED ISSUE #1888: mitmweb: --host Not Working
##### Steps to reproduce the problem:

mitmweb is not respecting --host. All hosts are ips, never domain names. "showhost" is displayed at bottom of mitmweb web page.

##### Any other comments? What have you tried so far?

I had reported this long ago. The issue was switches weren't implemented. Now they are but --host isn't working anyway.

##### System information

Mitmproxy version: 1.0.0
Python version: 3.5.2
Platform: Windows-10-10.0.14393
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Windows version: 10 10.0.14393  Multiprocessor Free

### PR DESCRIPTION
**Pull request by s4chin**

### CODE REVIEW

**Comment by s4chin** [comment]
Yes, it I copied it from the Python function. I think we should pass pretty_host in the JSON. Am I to add this here? https://github.com/mitmproxy/mitmproxy/blob/8f13f357adb6aa0e952eb99200ef3fbd5cc73c36/mitmproxy/tools/web/app.py

**Comment by mhils** [comment]
Yes, that's the right place. Thanks!

**Comment by s4chin** [comment]
I think this is done

**Comment by mhils** [comment]
Thanks. This does not fix #1888 as we now default to showing the pretty host, but the change we do here is the right one nonetheless.

**Pull request merged**
