### PR TITLE
fix vScroll calcuation, refs #5658

### PR DESCRIPTION
**Pull request by mhils**
This PR is an alternative fix for #5658: `calcVScroll` now bounds viewportTop so that additional checks should not be necessary.

@LIU-shuyi, can you verify that this works as expected please? 😃

### CODE REVIEW

**Comment by LIU-shuyi** [comment]
Hi, I tested it, but didn't work well in the scene i described in #5658. Same error as before.

the return value of calcVScroll() in onViewportUpdate() will not influence `viewportTop` directly.
viewport.scrollTop is set to viewport.scrollHeight in `AutoScroll.tsx: componentDidUpdate()`

base on your change , I add code as fallows, and it works:
```
diff --git a/web/src/js/components/FlowTable.jsx b/web/src/js/components/FlowTable.jsx
index 45f12e9d3..6bb1873b9 100644
--- a/web/src/js/components/FlowTable.jsx
+++ b/web/src/js/components/FlowTable.jsx
@@ -85,7 +85,10 @@ class FlowTable extends React.Component {
         })
 
         if (this.state.viewportTop !== viewportTop || !shallowEqual(this.state.vScroll, vScroll)) {
-            this.setState({ vScroll, viewportTop })
+            this.setState({
+                vScroll,
+                viewportTop: Math.min( viewportTop, vScroll.end * this.props.rowHeight),
+            });
         }
     }
```

**Comment by mhils** [comment]
Thanks! 🍰 Seems like I wasn't testing with enough rows. I've been able to reproduce it now, and incorporated your fix. Can you confirm that this works now? 😃

**Comment by LIU-shuyi** [comment]
Aha, the code works well this time.

**Comment by mhils** [comment]
Awesome, thanks for the initial PR and the quick confirmation! 🍰

**Pull request merged**
