### PR TITLE
fixing issue #1828

### PR DESCRIPTION
**Pull request by RobbBienert**

### CODE REVIEW

**Comment by mhils** [comment]
Thanks! Could you adjust the tests as well please? 😃

**Comment by RobbBienert** [comment]
If you can tell me what the errors mean we can talk about it ...

**Comment by mhils** [comment]
If you look at https://ci.appveyor.com/project/mhils/mitmproxy/build/3791#L1278, it should be clear where the errors come from. The offending test is `test/mitmproxy/addons/test_script.py::test_reloadhandler` 😃

**Comment by mhils** [comment]
Any update on this? 😃

**Comment by RobbBienert** [comment]
Should the method return `True` by default? The build systems messages are hardly to understand for a newbie to it.

**Comment by mhils** [comment]
This is the test in question: https://github.com/mitmproxy/mitmproxy/blob/5d0f7e5c41f3c553b993162abaef32c44ac22781/test/mitmproxy/addons/test_script.py#L43-L55

We previously reloaded on all files (and this has been tested). We now need to adjust the test so that it only expects reloads for files ending with `.py`.

**Comment by RobbBienert** [comment]
Hope this commit works, because neither my fork/checkout nor the local python installation contains any py.test file (Linux Mint Sarah).

**Comment by mhils** [comment]
Sorry for the late response - I think we can keep the `on_created` handler just like the `on_changed` one, i.e. trigger on new `.py` files. 😃

**Pull request closed without merging**
