### PR TITLE
Clipboard

### PR DESCRIPTION
**Pull request by mhils**
Add clipboard support to mitmproxy, thanks to @gato. Supersedes #448.

### CODE REVIEW

**Comment by mhils** [comment]
Hey @gato,

thanks again for the excellent PR for clipboard handling. I tested it extensively today and I really like that feature addition. I was a bit unsatisfied with the `g` / `G` shortcuts though - they felt a bit unintuitive. Here's my attempt on this. It's now just `g`, which is now followed by a `content / headers+content / url` prompt. In the flow list, both request and response are copied. For example, you get
```http
GET / HTTP/1.1
Host: mitmproxy.org
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Cookie: __utma=30234659.907313134.1422275306.1423261344.1423264742.8; __utmz=30234659.1422275306.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmc=30234659; __utmb=30234659.11.10.1423264742
Pragma: no-cache
Cache-Control: no-cache
Content-Length: 0

HTTP/1.1 200 OK
Server: nginx/1.1.19
Date: Fri, 06 Feb 2015 23:32:27 GMT
Content-Type: text/html
Last-Modified: Mon, 29 Dec 2014 20:56:57 GMT
Connection: keep-alive
Vary: Accept-Encoding
Expires: Fri, 06 Feb 2015 23:32:26 GMT
Cache-Control: no-cache
Content-Length: 11037

<!DOCTYPE html> ...
```
directly out of mitmproxy. In the flow details view, either request or response are copied, depending on the active window. What's your take on this? Prefer this or the previous approach? Any ideas how we can do better?

Thanks!
Max

**Comment by mhils** [comment]
For reference: This would fix #460 and #334.

**Comment by gato** [comment]
Hi @mhils ,
I think your solution is simpler, and you can even get the whole flow with 2 keypresses. I've tried it and works fine for me. 
So feel free to merge the changes.
Regards.
Marcelo
PS: next time, you don't need to create a PR and check it with me although I really appreciate you did it ;)

**Comment by mhils** [comment]
> PS: next time, you don't need to create a PR and check it with me although I really appreciate you did it ;)

You probably spent more time on that feature than I did, so not asking you would be very unwise. :wink: 

Anyways - merged! Great feature, happy to see that in the next release. :smiley:

Cheers,
Max

**Pull request merged**
