### PR TITLE
console error

### PR DESCRIPTION
**Pull request by sarthak212**
#3949

### CODE REVIEW

**Comment by sarthak212** [comment]
`unquote` function remove quote when executing command So i think we can apply `?` mark to last quotation.Is there any problem with this approach @mhils

**Comment by mhils** [comment]
Ok, now I think I understand the issue. We failed when we ended with an incomplete escape sequence before. @sarthak212: If you could add a test this can be merged. Thanks!

**Comment by sarthak212** [comment]
Thanks @mhils I have done some changes, Update me on further changes.

**Comment by mhils** [comment]
Awesome, thanks!

**Pull request merged**
