### PR TITLE
Organize examples

### LINKED ISSUE #1586: Organize Examples
##### Steps to reproduce the problem:
1. Visit https://github.com/mitmproxy/mitmproxy/tree/master/examples for the first time. 
2. Be overwhelmed. (@mitmproxy/devs may not be able to reproduce this)
##### What went wrong?

Our examples directory has grown organically and I feel there are too many too complex examples in there that scare users away. It's not really clear where to start.
##### What is the expected behavior?

We should guide users to the simpler, more frequently used examples like add_header.py, filt.py, modify_response_body.py or redirect_requests.py and hide the more complex ones.
##### Any other comments? What have you tried so far?

I would propose to split the examples folder into "beginner" and "complex" and (after this, in a second PR) add a README in the examples folder that guides the user. The beginner examples don't have to be trivial, but they should have a high usefulness/complexity ratio.

I'd be more than happy if a new contributor wants to pick that up and let us know which examples are helpful for mitmproxy beginners and which aren't! :smiley:

### PR DESCRIPTION
**Pull request by thiagoarrais**
Organizes examples as per #1586 

Fixes #1586

### CODE REVIEW

**Comment by thiagoarrais** [comment]
Note to self
---------

Before removing the WIP marker, remember to:

 - [ ] Check for broken refs to the following files in `docs`
   - [ ] add_header
   - [ ] modify_response_body
   - [ ] nonblocking
   - [ ] libpathod_pathoc
   - [ ] stickycookies
   - [ ] stream_modify
   - [ ] stream
   - [ ] tcp_message

**Comment by thiagoarrais** [comment]
I think this is ready. Should I squash the commits?

**Comment by mhils** [comment]
@thiagoarrais: Squashing @l33tLumberjack's commits would be great, yes. I see our CI systems are still not happy with the changes here, can we get the tests fixed as well? :smiley:

**Comment by thiagoarrais** [comment]
Commits squashed. Used the message from PR #1600. @l33tLumberjack, would you mind giving us a LGTM here?

**Comment by thiagoarrais** [comment]
Will check the tests next.

**Comment by l33tLumberjack** [comment]
LGTM

**Comment by thiagoarrais** [comment]
Tests fixed.

**Comment by thiagoarrais** [comment]
Ready to be merged.

**Comment by l33tLumberjack** [comment]
@mhils We have green lights across the board here ready to merge

**Comment by mhils** [comment]
Thanks guys!
I'll let @cortesi finish his docs update and then merge your PR and adjust the paths. We don't want the poor @cortesi deal with sphinx more than necessary. :wink:

**Comment by Kriechi** [comment]
@mhils: I think most of the major refactoring and moving stuff around is done now.
Should we try to get this PR ready again to merge it?
(rebase & fix conflicts)

**Pull request closed without merging**
