### PR TITLE
cleanup h2 and test

### PR DESCRIPTION
**Pull request by Kriechi**
taken from #1057
closes #1057

### CODE REVIEW

**Comment by mhils** [comment]
LGTM, but we have a traceback in the tests: https://travis-ci.org/mitmproxy/mitmproxy/jobs/123149852#L435

**Comment by mhils** [comment]
Any progress on this? :relaxed:

**Comment by Kriechi** [comment]
Sorry - to busy with other things. Feel free to close it for now (and the other PR).
The code changes itself are fine - only the new test is the problem - but this happens in current master as well, so no real benefit here.

**Comment by Kriechi** [comment]
I moved the new test to #1057

**Pull request merged**
