### PR TITLE
Add Filter message to mitmdump

### LINKED ISSUE #3904: Mitmdump option error
#### Problem Description
When passing random arguments to mitmdump it doesn't show any error.

1. Type mitmdump abc 

It doesn't show any flow after that just clientconnect and clientdisconnect on requests but no error about wrong argument. Mitmproxy show this kind of error. I am not sure this is supposed to behave like this or this is a bug.

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 6.0.0.dev (+116, commit 7791410)
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-5.3.0-kali2-amd64-x86_64-with-debian-kali-rolling

### PR DESCRIPTION
**Pull request by sarthak212**
fixes #3904

### CODE REVIEW

**Comment by Prinzhorn** [comment]
`print` does not respect `--quiet`, there is a logger thingy. But I don't know how you can access it, you'll find out.

https://github.com/mitmproxy/mitmproxy/blob/3cd37652709292cffa1bc733134cef5483489341/mitmproxy/addons/termstatus.py#L13-L17

**Comment by sarthak212** [comment]
Thanks @Prinzhorn I will update it.

**Comment by Prinzhorn** [comment]
@mhils check the original commit out :smile:  https://github.com/mitmproxy/mitmproxy/pull/3938/commits/6f94e8538f76523a864dbd54f667b0f709945b64 I think this was just a matter of figuring out how to access the logger in this place

**Comment by mhils** [comment]
Eh, ugly. But I'm convinced, let's do it as it is. :)

**Comment by mhils** [comment]
Thanks @sarthak212!

**Pull request merged**
