### PR TITLE
Wrap WSGI request handling in individual threads to prevent blocking.

### PR DESCRIPTION
**Pull request by zbuc**
Resolves issue 477

The only other idea I had was maybe tracking a reference to the threads so you could join them and kill them cleanly when mitmproxy shuts down, but it didn't seem critical.

Otherwise, seems to work great -- no more blocking.

### CODE REVIEW

**Comment by zbuc** [comment]
I'm not sure why this failed on Travis.

I just ran the tests locally and verified they passed:

```
(venv)kali@kali:~/repos/mitmproxy$ nosetests --with-cov --cov-report term-missing
......................................................................................................................................................................................................................................................................................................................................
---------- coverage: platform linux2, python 2.7.3-final-0 -----------
Name                            Stmts   Miss  Cover   Missing
-------------------------------------------------------------
libmproxy/__init__                  0      0   100%
libmproxy/cmdline                 166      0   100%
libmproxy/controller               72      0   100%
libmproxy/dump                    156      0   100%
libmproxy/encoding                 39      0   100%
libmproxy/filt                    225      0   100%
libmproxy/flow                    654     23    96%   198, 375, 379, 383, 412, 435-437, 558, 674, 677, 772-791, 938-940, 958, 961
libmproxy/onboarding/__init__       0      0   100%
libmproxy/onboarding/app           33      0   100%
libmproxy/protocol/__init__         1      0   100%
libmproxy/protocol/handle           6      0   100%
libmproxy/protocol/http           647     19    97%   120-123, 473, 821, 1145-1146, 1148, 1254, 1308-1315, 1426, 1439, 1441, 1469, 1474-1476
libmproxy/protocol/primitives     118      3    97%   93, 153, 238
libmproxy/protocol/tcp             56      2    96%   67, 74
libmproxy/proxy/__init__            2      0   100%
libmproxy/proxy/config            130      9    93%   28, 66, 101, 106-109, 123-124, 175
libmproxy/proxy/connection         96      0   100%
libmproxy/proxy/primitives         93     33    65%   30, 37, 42, 79, 83-88, 93-140
libmproxy/proxy/server            181      8    96%   183, 185, 200, 205, 222, 266-267, 271
libmproxy/script                   89      5    94%   27, 69, 71-72, 137
libmproxy/stateobject              26      2    92%   19, 29
libmproxy/utils                   124      0   100%
libmproxy/version                   8      0   100%
libmproxy/web/__init__             76     46    39%   16, 19-20, 27-28, 35-36, 43-44, 52-57, 60-67, 74-76, 116-120, 125-132, 138, 157-160, 163-164, 167-168, 171-172, 175-176
libmproxy/web/app                 129     78    40%   16-21, 30, 34, 38-43, 46-49, 54-55, 60, 68, 71, 75-80, 89, 96, 101, 106, 111-112, 117, 122, 127-129, 134-159, 164, 171, 180-194, 203-227
-------------------------------------------------------------
TOTAL                            3127    228    93%
----------------------------------------------------------------------
Ran 326 tests in 27.710s

OK
```

**Comment by mhils** [comment]
Hmm, travis is usually very good at spotting the weirdest race conditions (it feels like they have their servers running at 100% load...), so it might be that. I really appreciate the PR, but haven't found time to think through this. Sorry for the slow processing, but we don't want to merge this while the test suite shows still unexplained issues.

Thanks!
Max

**Comment by zbuc** [comment]
I've been running my branch for a while now (and working on an AJAXy WSGI app that runs inside mitmproxy) and noticed the web threads need to be daemonized.

Seems to have made the cpython Travis build happy, but not pypy.

**Comment by zbuc** [comment]
So it's an intermittent failure, indicating probably something with threads not respecting shared resources...

The test failure occurs because occasionally the test in `test_server.py` winds up returning a 200 response with contents:

```
<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml"><head><meta  content="text/html; charset=utf-8" http-equiv="Content-Type"/>\n\n\n<link  href="01-bootstrap.min.css" type="text/css" rel="StyleSheet"/>\n<link  href="03-sitestyle.css" type="text/css" rel="StyleSheet"/>\n<title>mitmproxy - mitmit</title></head><body><div class="container">\n   <h1> If you can see this, traffic is not passing through mitmproxy.</h1>\n\n<p><center>\n    <a class="btn btn-default btn-large" href="http://mitmproxy.org/doc/index.html">\n    Visit the Documentation\n    </a\n</center></p>\n\n</script>\n</body></html>
```

when it's expecting to see a 304.

Affected test code:

```
    def test_http(self):
        f = self.pathod("304")
        assert f.status_code == 304

        l = self.master.state.view[-1]  # In Upstream mode with SSL, we may already have a previous CONNECT request.
        assert l.client_conn.address
        assert "host" in l.request.headers
        assert l.response.code == 304
```

**Comment by cortesi** [comment]
Hi there. This is a concurrency issue, due to the fact that we permit access to the global Proxy object right from within the WSGI application. This is the simplest way to go at the moment, and can't be fixed without a substantial IPC layer or a locking mechanism. 

We have a set of work on the horizon that will help clarify the inter-thread comms situation here - I'd like to punt concurrent WSGI until then (hopefully the next release). Thank you very much for tackling this - hope to see you around in our commit log. :)

**Pull request closed without merging**
