### PR TITLE
Adding export raw http response

### PR DESCRIPTION
**Pull request by mckeimic**
Adding a new export type for raw http response, and changing export raw to export
raw_request to distinguish between the two. This is a proposed change for https://github.com/mitmproxy/mitmproxy/issues/3701

### CODE REVIEW

**Comment by ylmrx** [comment]
I wouldn't rename `raw->raw_request`, having `raw_response` is indeed useful.

**Comment by mhils** [comment]
Thanks! Not exporting responses clearly is an oversight. Adding to what @ylmrx said, maybe we just want to go for `raw_request`, `raw_response` and `raw` (which outputs both combined)?

**Comment by Kriechi** [comment]
@mckeimic looks like we have a merge conflict now - would you mind looking into it?

**Comment by mhils** [comment]
Ah, I wanted to merge those the other way around. I'll take care of the merge conflict, this should be straightforward to fix :)

**Comment by mckeimic** [comment]
You folks are lightning fast! Thank you!

**Pull request merged**
