### PR TITLE
[web] fix FlowTable.scrollIntoView

### PR DESCRIPTION
**Pull request by gzzhanghao**
`FlowTable.scrollIntoView` doesn't work correctly when there are multiple flows with same value for sorting function.

Reproduce by:

- select a flow whose method is `GET`
- sort flows by method field

### CODE REVIEW

**Comment by mhils** [comment]
Couldn't we fix that by using `_.sortedIndexOf` in `StoreView.index`?
(That would also require updating `StoreView.add` to manually use `_.sortedIndexBy`)

**Comment by gzzhanghao** [comment]
@mhils We can also use `_.sortedIndexOf` in `FlowTable.scrollIntoView`. So the problem becomes what `StoreView.index` actually stands for :confused:

**Comment by mhils** [comment]
Right - let's just rename that to indexOf then?

**Comment by gzzhanghao** [comment]
@mhils Sounds good, pushed.

**Pull request merged**
