### PR TITLE
Display errors on sys.stderr

### PR DESCRIPTION
**Pull request by JessicaFavin**
Fix issue #3339

### CODE REVIEW

**Comment by mhils** [comment]
Thanks for the PR! Can you please adjust the tests as well?

**Comment by JessicaFavin** [comment]
Hi ! I adusted the tests as well, thanks for reminding me !
Building still fails on both AppVeyor and Travis though with "py37: commands failed" and "py36: commands failed" I'm not sure I understand how to fix this... Do you have any hints ?

**Comment by mhils** [comment]
Thanks! We enforce 100% test coverage for all addons, which is why CI is failing: https://travis-ci.org/mitmproxy/mitmproxy/jobs/450507976#L1993 :)

**Comment by JessicaFavin** [comment]
Thanks ! I'll fix that

**Comment by JessicaFavin** [comment]
It's all fixed now :)

**Comment by mhils** [comment]
Awesome, thanks again! 🍰 😃

**Pull request merged**
