### PR TITLE
Fix for loading HAR that contains BOM

### PR DESCRIPTION
**Pull request by dstd**
#### Description

Fiddler adds BOM when exporting, which caused HAR detection to fail and attempt to read HAR content as a serialized state.

#### Checklist

 - [x] I have updated tests where applicable.
 - [x] I have added an entry to the CHANGELOG.

### CODE REVIEW

**Review by mhils — COMMENTED** [review]
Thanks! Could you please add an example HAR file in https://github.com/mitmproxy/mitmproxy/tree/main/test/mitmproxy/data/har_files for test coverage?

https://github.com/mitmproxy/mitmproxy/blob/bd39c7b96fd74f0ff83d69acf93898dbcdce9310/test/mitmproxy/io/test_io.py#L30-L40 picks those up automatically.

**Comment by mhils** [comment]
friendly bump :)

**Comment by dstd** [comment]
@mhils yeah, thanks) Haven't had a PC in reach for a while, and forgot about the sample. Added

**Review by mhils — APPROVED** [review]
Thanks! 🍰

**Pull request merged**
