### PR TITLE
Charset in meta tags

### PR DESCRIPTION
**Pull request by rjt-gupta**
Added tests for #3150

### CODE REVIEW

**Comment by rjt-gupta** [comment]
This is ready for review.

**Comment by mhils** [comment]
Awesome. thanks! 🍰

**Comment by mhils** [comment]
I squash-merged this with a pointer to https://github.com/mitmproxy/mitmproxy/pull/3150 in the comments. Please retain the original commit history next time so that we can give the author proper credit. Thanks!

**Comment by rjt-gupta** [comment]
Yeah Okay.

**Pull request merged**
