### PR TITLE
Fix load flows crash

### PR DESCRIPTION
**Pull request by mattweidner**
Fixed a crash when trying to load flows from a file that doesn't exist.
Added os.path.expanduser() before open() calls with user supplied paths.

### CODE REVIEW

**Comment by mhils** [comment]
This looks great, thanks! 😃 
The tests are currently failing as we enforce 100% line coverage for everything in `mitmproxy.addons` (https://ci.appveyor.com/project/mhils/mitmproxy/build/5243#L1368). Could you please add a basic tests that verfies that `view.load` does not crash? 😊 

Thanks again! 🍰 🎉 
Max

**Comment by mattweidner** [comment]
Thank you for your patience. I am a veteran programmer but new to distributed development. I love mitmproxy and very excited to be able to give back to the community.

**Comment by mhils** [comment]
Fantastic, thanks! 

How are you doing your merge/rebase on master? The commit history seems to be a bit messed up. I'll just squash for now, but you may want to fix that. 

If you have any questions when hacking on mitmproxy, please feel free to join us on Slack and ask if you want! 😃

**Comment by mattweidner** [comment]
Yes, looking through my bash history it seems I did a `git merge upstream/master`. I did not realize it would be a mess for you upstream. Sorry for that rookie mistake. What, then, is the proper way to update my local feature branch with upstream changes after I have submitted a pull request? I can move this discussion to Slack if you prefer.

**Comment by Kriechi** [comment]
This is what I usually do to rebase an existing PR:

```
git checkout master
git pull upstream/master
(make sure you fast-forward all upstream changes to your fork's master branch)
(if you are creating a merge commit, you messed up something)
git checkout <pr-branch>
git rebase -i master
(verify all commits you want in the PR are listed, then save & exit your editor)
git push -f
```

Make sure that `<...>mitmproxy/mitmproxy.git` is added as remote `upstream`.
(https://help.github.com/articles/configuring-a-remote-for-a-fork/)

Of course, as always, with git there are multiple strategies what to do when, including short-cuts and longer versions of the same commands.

**Pull request merged**
