### PR TITLE
WIP: Implement dark mode for mitmweb

### PR DESCRIPTION
**Pull request by oxr463**
Bug: https://github.com/mitmproxy/mitmproxy/issues/3886

Reference:

- https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

- https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

### CODE REVIEW

**Comment by oxr463** [comment]
```python
self.app = app.Application(
            self, self.options.web_dark_mode
        )
```

Adapted from: https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/web/master.py#L46

**Comment by mhils** [comment]
Thanks for the preliminary PR! I think I would be in favor of just respecting the browser's `prefers-color-scheme` setting, everything else seems overkill to me. Most crucially, I don't want to maintain additional dependencies and options.

**Comment by oxr463** [comment]
@mhils will do.

**Comment by oxr463** [comment]
**Bootstrap Variables**

```
@gray-darker:  lighten(#000, 13.5%); // #222
@gray-dark:    lighten(#000, 20%);   // #333
```

Source: `node_modules/bootstrap/less/variables.less`

**Comment by oxr463** [comment]
See: https://stackoverflow.com/a/56757527/8507637

image

**Comment by mhils** [comment]
Closing this here, see https://github.com/mitmproxy/mitmproxy/pull/3903#issuecomment-609464530. I'm fine with having CSS that auto-adjusts to the browser settings, but we don't need a separate setting within mitmproxy for this.

**Pull request closed without merging**
