### PR TITLE
added svg image preview support

### PR DESCRIPTION
**Pull request by Thanush19**
#### Checklist

 - [ ] I have updated tests where applicable.
 - [ ] I have added an entry to the CHANGELOG.
i have added image preview support in  /web/src/components/contentviews/HttpMessage/tsx

### CODE REVIEW

**Review by mhils — APPROVED** [review]
Thanks!

**Comment by 0o0ooo** [comment]
May I ask when I can use this fixed package? I ran 10.3.0 but still haven't fixed this issue. Thank you for your reply

**Comment by mhils** [comment]
This fix is in the latest release already. What content-type header do you have?

**Comment by 0o0ooo** [comment]
image

**Comment by 0o0ooo** [comment]
> This fix is in the latest release already. What content-type header do you have?

image
The type is image/svg+XML, but the preview image is still not displayed

**Comment by 0o0ooo** [comment]
Could you please take a look at my question? Thank you.

**Pull request merged**
