### PR TITLE
Show tracebacks on mitmproxy error pages

### PR DESCRIPTION
**Pull request by dwfreed**
Instead of the repr of the exception, which is basically useless, show
the full traceback on the error page.

### CODE REVIEW

**Comment by Kriechi** [comment]
Wouldn't it be just easier to get rid of the html stuff and render plain text?

**Comment by dwfreed** [comment]
But then you wouldn't have the HTML title with the HTTP status

**Comment by mhils** [comment]
I'm not sure if this is a great idea, this introduces a potential information leak in some contexts. @cortesi, thoughts?

**Comment by dwfreed** [comment]
Not really much more than printing the repr(exception) already does

**Comment by dwfreed** [comment]
It needs some fixing anyway: https://travis-ci.org/mitmproxy/mitmproxy/jobs/135699606#L421

**Comment by dwfreed** [comment]
Oh, even better, that test passes locally, but not on travis

**Comment by dwfreed** [comment]
I see, it's because the data is random, so test failure there is non-deterministic

**Comment by cortesi** [comment]
This is an idea worth considering, but I'm afraid that having considered it, I'm not in favour of it. ;) We should expose as little as possible of our internal workings to the proxy clients (which may be hostile, or we may be trying to be covert, etc.). In fact, the exception repr itself should be removed altogether. Instead, we should expose error information to the controller of the proxy - that is, in the eventlog for mitmproxy console and mitmweb, and printed to screen in mitmdump.

**Comment by dwfreed** [comment]
From the discussion on Slack, this likely isn't going to be merged, so I'll close it.  I'll put together some improved logging handling next week.

**Pull request closed without merging**
