### PR TITLE
Don't write to closing streams, fix #5363

### LINKED ISSUE #5363: 'socket.send() raised exception.' on stderr
#### Problem Description
In a long-running session of mitmdump that captures traffic of all surfing on an iPad, standard error logs a bunch of
```
socket.send() raised exception.
```
Nothing else is logged. Subjectively every now and then this is logged a browser tab stalls on the iPad. Looking at where the message comes from (`asyncio/*_events.py`) I believe this is the result of a socket already being dead when the HTTP/2 PING is sent periodically. 
It looks to me like asyncio is catching this exception but mitmproxy is not made aware that the server connection is actually dead. Trying to use the dead connection often enough results in this log message:

```
            if self._conn_lost >= constants.LOG_THRESHOLD_FOR_CONNLOST_WRITES:
                logger.warning('socket.send() raised exception.')
```
I do not see any method to query the status of `self._conn_lost` which would help fixing this.

#### System Information
Mitmproxy: 9.0.0.dev (+151, commit 46f01ad)
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1n  15 Mar 2022
Platform:  Linux-4.18.0-383.el8.x86_64-x86_64-with-glibc2.28

### PR DESCRIPTION
**Pull request by mhils**
Catching up on older issues - here's a simpler fix for #5363. :) @EndUser509, does that look somewhat correct to you?

### CODE REVIEW

**Comment by decathorpe** [comment]
Note that this broke the WireGuard mode, because `mitmproxy_wireguard.TcpStream` does not implement `is_closing` method.

**Comment by mhils** [comment]
Eh, well spotted. Why is CI not catching this?

**Comment by decathorpe** [comment]
Looks like the wireguard ServerInstance test was not run during CI?

**Comment by mhils** [comment]
https://github.com/mitmproxy/mitmproxy/actions/runs/3106426607/jobs/5033294929#step:7:1000 looks right. Likely we don't catch this because it happens during teardown. I would have expected mypy to catch this though.

**Comment by decathorpe** [comment]
I assume TcpStream.is_closing is never called because we're monkeypatching `ConnectionHandler.handle_client` with a method that doesn't call `is_closing` on the stream?

**Comment by mhils** [comment]
Yeah, that explains the working test. 👍 
Here's why mypy isn't complaining:
```diff
diff --git a/mitmproxy/proxy/server.py b/mitmproxy/proxy/server.py
index 1341564ad..4781294a9 100644
--- a/mitmproxy/proxy/server.py
+++ b/mitmproxy/proxy/server.py
@@ -367,6 +367,7 @@ class ConnectionHandler(metaclass=abc.ABCMeta):
                 elif isinstance(command, commands.SendData):
                     writer = self.transports[command.connection].writer
                     assert writer
+                    reveal_type(writer)
                     if not writer.is_closing():
                         writer.write(command.data)
                 elif isinstance(command, commands.CloseConnection):
```

```
λ tox -e mypy
mypy run-test: commands[0] | mypy
mitmproxy/proxy/server.py:370: note: Revealed type is "Union[asyncio.streams.StreamWriter, Any, mitmproxy.net.udp.DatagramWriter]"
Success: no issues found in 273 source files
ERROR: InvocationError for command /mnt/c/Users/user/git/mitmproxy/.tox/linux/mypy/bin/mypy (exited with code 1)
```

`wg.TcpStream` registers as `Any` somehow, presumably because mypy can't find the definitions. Do we need to set `py.typed` somewhere or something like this?

**Comment by decathorpe** [comment]
> Do we need to set py.typed somewhere or something like this?

No idea :( This is the first time I'm working with a "native" Python module. But maturin already includes the `.pyi` and `py.typed` files automatically, so that shouldn't be it.

**Comment by decathorpe** [comment]
I went ahead and implemented `is_closing` on `TcpStream` as it was pretty easy to do. I'll bundle in the fix for the `InvalidStateError` race condition and then I'll publish a new release :)

**Comment by decathorpe** [comment]
Release 0.1.10 of mitmproxy_wireguard should fix this problem:
https://github.com/decathorpe/mitmproxy_wireguard/releases/tag/0.1.10

**Pull request merged**
