### PR TITLE
Fix crash when duplicating flow

### LINKED ISSUE #2086: crash when trying to duplicate a flow
##### Steps to reproduce the problem:

1. Start as usual (i.e. `mitmproxy -p $port`).
1. Record at least one flow.
2. Press <kbd>Shift</kbd><kbd>D</kbd> to duplicate a flow.

Crashes every time. Stacktrace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/window.py", line 84, in keypress
    k = super().keypress(size, k)
  File "/usr/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 417, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/usr/lib/python3.6/site-packages/urwid/listbox.py", line 987, in keypress
    self.make_cursor_visible((maxcol,maxrow))
  File "/usr/lib/python3.6/site-packages/urwid/listbox.py", line 939, in make_cursor_visible
    focus_widget, pos = self.body.get_focus()
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 284, in get_focus
    f = FlowItem(self.master, self.master.view.focus.flow)
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 123, in __init__
    w = self.get_text()
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/flowlist.py", line 132, in get_text
    max_url_len=cols,
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/common.py", line 427, in format_flow
    acked = f.reply.state == "committed",
AttributeError: 'NoneType' object has no attribute 'state'
```

##### System information

Mitmproxy version: 2.0.0 (release version)
Python version: 3.6.0
Platform: Linux-4.9.11-1-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.0.2k  26 Jan 2017
Linux distro: arch

### PR DESCRIPTION
**Pull request by iharsh234**
As discussed with @cortesi about this #2096  over IRC . Now it will set reply to DummyReply whenever we duplicate any flow. #2086 .

### CODE REVIEW

**Comment by cortesi** [comment]
Hi there - this looks good. Could you please squash the commits in this PR together, and give the commit a germane title (something like "Fix crash when duplicating flow") and we'll merge.

**Comment by cortesi** [comment]
I'm not sure about just setting a dummy reply on in the constructor. We probably want things to blow up rather than silently ignoring interactions when we unexpectedly don't have a .reply set. This is a delicate bit of the codebase, and I'm leery of unanticipated consequences here. I say we fix the immediate bug, and table a re-thinking of the reply mechanism later on.

**Comment by mhils** [comment]
Right, I'm happy with both. In this case, we should fix it [here](https://github.com/mitmproxy/mitmproxy/blob/5cf268b012697730c37df9d46c2f580f8184ef08/mitmproxy/tools/console/common.py#L427)?

**Comment by cortesi** [comment]
Hmm.. the copy method is still the right place for the fix - just say that if the flow being copied  has a non-null reply, we create a dummy reply in the duplicate.

**Comment by cortesi** [comment]
@iharsh234 Just to recap the discussion here and a bit of chat on slack:

- Make sure there's one commit with a clear name.
- Make sure DummyReply is initialised
- Tweak the code slightly to only create the dummy reply if the flow being copied has a non-None reply attribute.

Apologies for the slightly confusing progression of comments here, but that's how the sausage is made. :)

**Pull request merged**
