### PR TITLE
Only emit "serverconnect" after successfully connecting

### LINKED ISSUE #3880: ServerConnection.ip_address is not populated inside `serverconnect` event
#### Problem Description

Inside the `serverconnect` event the `ip_address` property is not populated, it is `None`. The `address` property is correctly populated. Since the connection is open I would expect the IP address to be known and the property to be available.

#### Steps to reproduce the behavior:

`mitmdump --scripts conn.py`

```python
def serverconnect(conn):
  print('-------connect--------------')
  print(conn.id)
  print(conn.address)
  print(conn.ip_address)
  print('-------/connect--------------')

def serverdisconnect(conn):
  print('----------disconnect-----------')
  print(conn.id)
  print(conn.address)
  print(conn.ip_address)
  print('----------/disconnect-----------')
```

Output

```
-------connect--------------
ab301a58-2366-4025-bab9-77c2bdfe74e6
('prinzhorn.it', 80)
None
-------/connect--------------

----------disconnect-----------
ab301a58-2366-4025-bab9-77c2bdfe74e6
('prinzhorn.it', 80)
('87.98.150.101', 80)
----------/disconnect-----------
```

#### System Information

```
Mitmproxy: 5.0.1
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-5.3.0-45-generic-x86_64-with-Ubuntu-19.10-eoan
```

### PR DESCRIPTION
**Pull request by Prinzhorn**
Fixes #3880

It looks like there are no tests for events so far? I'm not familiar with Python especially testing frameworks and stuff. But I guess it makes sense to look into that?

### CODE REVIEW

**Comment by Prinzhorn** [comment]
I must assume my changes have nothing to do with the two failed checks.

**Comment by mhils** [comment]
Awesome, thanks! 🍰 

The proxy core (everything in mitmproxy.proxy) has a terrible test coverage unfortunately, mostly because I had much less experience, we did much less testing back then in general, and the fact that I/O code is just ugly to test. 🙊

**Comment by mhils** [comment]
Regarding the failed tests: Looks like we aren't pinning mypy properly with Github Actions, and new mypy releases tend to complain about new things in existing code. Not your fault, I'll pin it properly as we speak.

**Comment by Prinzhorn** [comment]
> The proxy core (everything in mitmproxy.proxy) has a terrible test coverage unfortunately, mostly because I had much less experience, we did much less testing back then in general, and the fact that I/O code is just ugly to test. speak_no_evil

If I ever feel like getting into that kind of stuff I'll let you know. I have a thing about finding weird edge cases :smile:

**Pull request merged**
